# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci_sequence(max_value=None):
    x0 = 0
    x1 = 1
    while True:
        yield x1
        x0, x1 = x1, x0 + x1
        if max_value and x1 > max_value:
            break

even_fib_numbers_4mil_max = [fib_number for fib_number in fibonacci_sequence(4000000) if fib_number % 2 == 0]
print sum(even_fib_numbers_4mil_max)